### ISSUE TITLE
Are Red and Blue swapped?

### ISSUE THREAD

**Issue by MrBryonMiller** [adafruit/Uncanny_Eyes#3]
I noticed on my build that the default sclera does not appear like the PNG file.  The PNG file shows the edges and the veins as reddish while my display shows blueish. Full disclosure - I have made quite a few modifications.  I am showing two eyes (each one is 120x120) on one AdaFruit 480x320 TFT display.  This display uses a HX8357 rather than any of the display boards the library currently supports.  Because of the hardware device differences I thought this blueish characteristic must be my problem, so I set out to find it.  I came across the 4 MADCTL settings.  I realized each one of the 4 settings were such that the display was set to expect GBR rather than RGB.  Once I cleared bit 3 in the mirrorTFT control the colors as shown on my build appeared as I expected. 

Thing is, I checked one of the other controllers the library software is designed for (the ST7735) and I discovered that its MADCTL register is the same way that is it is in the HX8357.  So it seems displays using the ST7735 would also have the Red and Blue swapped.  I do not have such a display so I cannot confirm.

Issue is - am I right about the colors being off of is my head screwed on backwards?  If the latter I truly apologize for opening this issue.

**Comment by ladyada** [comment]
ST7735 is definitely OK as is - each TFT can have different RGB ordering, you'll have to mess with MADCTL to get it to be right but we dont know what those are.
