### ISSUE TITLE
Hallowing supported?

### ISSUE THREAD

**Issue by adamsd5** [adafruit/Uncanny_Eyes#4]
Sorry if this is a bad place to ask, but I'm trying to compile and upload this to a Hallowing board.  I have blink working, this code downloaded, and all the required libraries (I think) installed.  I am getting this compile error... any suggestions?

Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Adafruit Hallowing M0"

C:\Users\adams\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library\Adafruit_ZeroDMA.cpp: In member function 'void Adafruit_ZeroDMA::setPriority(dma_priority)':

C:\Users\adams\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library\Adafruit_ZeroDMA.cpp:258:8: error: 'struct Dmac' has no member named 'Channel'

  DMAC->Channel[channel].CHPRILVL.bit.PRILVL = pri;

        ^

exit status 1
Error compiling for board Adafruit Hallowing M0.

**Comment by PaintYourDragon** [comment]
Please fetch the latest Adafruit_ZeroDMA library. There was a window of a few hours where it contained a bit of M4-specific code. Fixed now.
